name: localization_generator
description: localization generator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  path_provider: ^2.0.7
  source_gen: ^1.1.1
  fast_immutable_collections: ^7.0.3

dev_dependencies:
  build_runner: ^2.0.1